import type { Metadata } from 'next';
import { Barlow, Barlow_Condensed, Bellefair } from 'next/font/google';
import './globals.css';

const bellefair = Bellefair({
	variable: '--font-bellefair',
	weight: '400',
	display: 'swap',
});

const barlow = Barlow({
	variable: '--font-barlow',
	weight: '400',
	display: 'swap',
});

const barlowCondensed = Barlow_Condensed({
	variable: '--font-barlow-condensed',
	weight: '400',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${bellefair.variable} ${barlow.variable} ${barlowCondensed.variable} antialiased relative`}>
				{/* <div className='design-overlay'>
					<Image
						src={DesktopDestinationA}
						alt=''
					/>
				</div> */}
				<>{children}</>
			</body>
		</html>
	);
}
